server:
  port: ${PORT}

spring:
  application:
    name: login

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_HOST}:8761/eureka

sns:
  kakao:
    id: ${KAKAO_CLIENT_ID}
    url: ${KAKAO_REDIRECT_URL}
  naver:
    id: ${NAVER_CLIENT_ID}
    url: ${NAVER_REDIRECT_URL}
    secret: ${NAVER_CLIENT_SECRET}

gateway:
  url: ${GATEWAY_URL}